basic_app/urls.py
from django.conf.urls import url

from basic_app import views

# TEMPLATE URLS!
app_name = 'basic_app'

urlpatterns = [
    #url(r'^$',views.index,name="index"),
    url(r'^register/$',views.register,name='register'),
    url(r'^ShopKeeper_login/$',views.ShopKeeper_login,name='ShopKeeper_login'),
    url(r'^UserFeedback/$',views.UserFeedback,name='UserFeedback'),
     
]

secondproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('',views.index,name='index'),
    path('logout/',views.ShopKeeper_logout,name='logout'),
    path('special/',views.special,name='special'),
    

]

basic_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from phone_field import PhoneField



# Create your models here.

class ShopKeeperRegistration(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #Additional Fields
    phone_number = PhoneField(blank=True,help_text='Contact phone number with country code')
    #number = models.IntegerField()
    

    def __str__(self):
        return self.user.username


class UserFeedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    Feedback = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import ShopKeeperRegistration,UserFeedback

from phone_field import PhoneField

class ShopKeeperRegistrationForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())
    #phone_number = PhoneField(blank=True,help_text='Contact phone number with country code')

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password',)

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = ShopKeeperRegistration
        fields = ('phone_number',)


class UserFeedbackForm(forms.ModelForm):

    class Meta():
        model = UserFeedback
        fields = '__all__'

basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from basic_app.forms import ShopKeeperRegistrationForm,UserProfileInfoForm,UserFeedbackForm


# for login we are importing following
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request,'basic_app/index.html',)


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def ShopKeeper_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    '''
    user_form = ShopKeeperRegistrationForm()
    profile_form = UserProfileInfoForm()
    '''

    if request.method == "POST":
        user_form = ShopKeeperRegistrationForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit=False)
            profile.user = user 

            if 'number' in request.FILES:
                profile.number = request.FILES['phone_number']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = ShopKeeperRegistrationForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def ShopKeeper_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                #return HttpResponseRedirect(reverse('conformation_login'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request,'basic_app/login.html',{})


def UserFeedback(request):

    form = UserFeedbackForm()

    if request.method == 'POST':
        
        form = UserFeedbackForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

        else:
            print("Error Form!")

    else:
        return render(request,'basic_app/UserFeedback.html',{'form':form})


'''

def conformation_login(request):
    return HttpResponse("You are logged in!")
'''

templates/basic_app/UserFeedback.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please fill the User Feedback Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>


{% endblock %}

templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <nav class = "navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO Index Page</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:UserFeedback' %}" >UserFeedback</a></li>

                    {% if user.is_authenticated %}
                        <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'basic_app:ShopKeeper_login' %}">Login</a></li>
                    {% endif %}



                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock  %}
        </div>

        

    </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:ShopKeeper_login' %}" method="post" >
        {% csrf_token %}
        
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">


    </form>


</div>


{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering! </h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">

        </form>


    {% endif %}

</div>

{% endblock %}